### ISSUE TITLE
How to test on VOC2012

### ISSUE THREAD

**Issue by Zhong1015** [yu-gi-oh-leilei/SADCL#1]
Hello, @yu-gi-oh-leilei , I am very interested in your work. You have researched and organized many label image classification tasks, which have been immensely helpful to me. Much of my current research and experimentation are based on the code you have provided. First of all, I would like to express my gratitude for the work you have done before. Currently, I am encountering difficulties when testing my model on VOC2012. Since VOC2012 does not provide complete test labels, I am unable to conduct local testing and need to upload it to the official server for evaluation. However, I do not have the code to generate the required txt files. If you could provide the relevant code, I would be extremely grateful. Once again, thank you for your relevant work.

**Comment by yu-gi-oh-leilei** [comment]
You can refer to
https://github.com/yu-gi-oh-leilei/SADCL/blob/ba9a7ec9dcf21a6afb2977889996a8c0319ba2f3/code/lib_sadcl/engine.py#L321
and
https://github.com/yu-gi-oh-leilei/SADCL/blob/ba9a7ec9dcf21a6afb2977889996a8c0319ba2f3/code/lib_sadcl/engine.py#L244

I hope that will help you.

**Comment by Zhong1015** [comment]
> You can refer to
> 
> https://github.com/yu-gi-oh-leilei/SADCL/blob/ba9a7ec9dcf21a6afb2977889996a8c0319ba2f3/code/lib_sadcl/engine.py#L321
> 
> 
> and
> https://github.com/yu-gi-oh-leilei/SADCL/blob/ba9a7ec9dcf21a6afb2977889996a8c0319ba2f3/code/lib_sadcl/engine.py#L244
> 
> I hope that will help you.

Thank you for your reply, it will be very helpful for me. In addition, I have encountered another issue. Despite conducting extensive searches online, I still cannot find the 'Labels_Train.txt' and 'Labels_Test.txt' files for NUSWIDE. I was wondering if you have these two files or if you are using the CSV format?

**Comment by yu-gi-oh-leilei** [comment]
Feel free to contact me if you have any questions.
https://drive.google.com/drive/folders/1_e2Ek4dAIgbFDKkN7LXL0lOhkOSxTFpL?usp=sharing

**Comment by Zhong1015** [comment]
> Feel free to contact me if you have any questions. https://drive.google.com/drive/folders/1_e2Ek4dAIgbFDKkN7LXL0lOhkOSxTFpL?usp=sharing

Thank you very much for providing the document!
