### ISSUE TITLE
About Visualization maps

### ISSUE THREAD

**Issue by Zhong1015** [yu-gi-oh-leilei/SADCL#2]
Hello, after reading your paper, I was contemplating that SARL is a module similar to Query2Label, which aims to locate regions of interest in images based on categories. I noticed in the paper that you visualized the SARL module, and I'm curious about the method you used for attention visualization. Specifically, I'm wondering if you targeted specific layers or heads, or if you averaged across multiple heads for visualization. I'm not sure if my understanding of the above is correct, and I would appreciate it if you could clarify my doubts at your convenience!

**Comment by yu-gi-oh-leilei** [comment]
Hello, @Zhong1015 !While the visualizations across different layers may not show significant variation, I recommend focusing on the final layer (last floor) for analysis.
If you have any questions, you can add WeChat ( 'n859432589')
